<a href="https://colab.research.google.com/github/Machine-Learning-Visao-Computacional-T1/CodigoDosAlunos/blob/main/Semana3/Exemplos_praticos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import time
import random

print("Gerando 1 MILHÃO de acessos de usuários no servidor...")
# Gera 1 milhão de acessos, mas os IDs dos clientes vão só do 1 ao 500 (muita repetição)
acessos_servidor = [random.randint(1, 500) for _ in range(1000000)]

print(f"Total de cliques registrados: {len(acessos_servidor)}\n")
print("Filtrando usuários únicos...")

# Marcando o tempo e usando o SET
inicio = time.time()

usuarios_unicos = set(acessos_servidor)

fim = time.time()
tempo_gasto = fim - inicio

# Resultado
print(f"Usuários reais (únicos) encontrados: {len(usuarios_unicos)}")
print(f"Tempo gasto para varrer 1 MILHÃO de registros: {tempo_gasto:.5f} segundos")

Gerando 1 MILHÃO de acessos de usuários no servidor...
Total de cliques registrados: 1000000

Filtrando usuários únicos...
Usuários reais (únicos) encontrados: 500
Tempo gasto para varrer 1 MILHÃO de registros: 0.02706 segundos


In [7]:
# Criando uma base de dados vazia (Lista)
tabela_clientes = []

# Preenchendo com 50.000 registros (Dicionários)
print("Baixando dados do servidor...")
for id_cliente in range(50000):
    registro = {
        "id": id_cliente,
        "nome": f"Cliente VIP {id_cliente}",
        "score_credito": random.randint(300, 1000),
        "ativo": True
    }
    tabela_clientes.append(registro)

print(f"Base carregada com sucesso! Total de linhas: {len(tabela_clientes)}\n")

# Consultando um dado específico no meio do Big Data
linha_desejada = 45999
print("--- DADOS DO CLIENTE 45999 ---")
print(f"Nome: {tabela_clientes[linha_desejada]['nome']}")
print(f"Score: {tabela_clientes[linha_desejada]['score_credito']}")

Baixando dados do servidor...
Base carregada com sucesso! Total de linhas: 50000

--- DADOS DO CLIENTE 45999 ---
Nome: Cliente VIP 45999
Score: 526


In [13]:
# Importando a famosa biblioteca de Machine Learning
from sklearn.datasets import load_iris

# Carregando o dataset pré-carregado
dataset_flores = load_iris()

print("--- ANALISANDO A ESTRUTURA DO DATASET ---")
# Vai mostrar as "chaves" do dicionário gigante
print(f"1. Chaves disponíveis no Dicionário: {dataset_flores.keys()}\n")

print(f"2. Nomes das colunas (Features): {dataset_flores['feature_names']}")
print(f"3. Nomes das categorias que a IA vai prever: {dataset_flores['target_names']}\n")

# Mostrando o tipo de dado real das medidas
print("--- ANALISANDO OS TIPOS DE DADOS ---")
print(f"Tipo da variável de dados: {type(dataset_flores['data'])}") # Vai mostrar <class 'numpy.ndarray'>

print("\n--- MOSTRANDO AS 5 PRIMEIRAS LINHAS DA MATRIZ NUMPY ---")
print(dataset_flores['data'][:5])
print(dataset_flores['target'])
print(dataset_flores['DESCR'])

--- ANALISANDO A ESTRUTURA DO DATASET ---
1. Chaves disponíveis no Dicionário: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

2. Nomes das colunas (Features): ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
3. Nomes das categorias que a IA vai prever: ['setosa' 'versicolor' 'virginica']

--- ANALISANDO OS TIPOS DE DADOS ---
Tipo da variável de dados: <class 'numpy.ndarray'>

--- MOSTRANDO AS 5 PRIMEIRAS LINHAS DA MATRIZ NUMPY ---
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
.. _iris_dataset:

Iris plants dataset
--------------------

**Data

In [5]:
import csv
import urllib.request

# 1. Puxando o CSV do Titanic direto do GitHub (Dados Brutos)
print("Baixando dataset do Titanic da Internet...")
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
resposta = urllib.request.urlopen(url)
linhas = [linha.decode('utf-8') for linha in resposta.readlines()]

# 2. Transformando em uma Lista de Dicionários!
leitor = csv.DictReader(linhas)
passageiros = list(leitor)

print(f"Sucesso! Temos os dados de {len(passageiros)} passageiros.\n")

# 3. Analisando o Tipo de Dado do primeiro passageiro
print("--- DADO BRUTO ---")
print(f"Nome: {passageiros[0]['Name']}")
print(f"Idade do passageiro 0: {passageiros[0]['Age']}")
print(f"TIPO PRIMITIVO DA IDADE: {type(passageiros[0]['Age'])}\n") # Vai mostrar STRING!

# 4. Limpando os dados com o Try/Except e List Comprehension
print("--- LIMPEZA E CONVERSÃO (CASTING) ---")
idades_limpas = []

for p in passageiros:
    try:
        # Tenta converter a string para Float
        idade_numero = float(p['Age'])
        idades_limpas.append(idade_numero)
    except ValueError:
        # Alguns passageiros não têm a idade preenchida (está vazio).
        # O try/except evita que o Colab exploda aqui!
        continue

print(f"Conseguimos converter as idades de {len(idades_limpas)} passageiros.")
print(f"Exemplo das 5 primeiras idades (agora como Float): {idades_limpas[:5]}")

Baixando dataset do Titanic da Internet...
Sucesso! Temos os dados de 891 passageiros.

--- DADO BRUTO ---
Nome: Braund, Mr. Owen Harris
Idade do passageiro 0: 22
TIPO PRIMITIVO DA IDADE: <class 'str'>

--- LIMPEZA E CONVERSÃO (CASTING) ---
Conseguimos converter as idades de 714 passageiros.
Exemplo das 5 primeiras idades (agora como Float): [22.0, 38.0, 26.0, 35.0, 35.0]
